(in-package :t2l)
(setq prules '((:S x)
               (:S y)
               (:S :S + :S)
               (:S :S - :S)
               (:S [ :S ])))
(setq prules '((:S 5 :A)
               (:S :S :S)
               (:A -3)
               (:A -2)
               (:A -1)
               (:A 1)
               (:A 2)
               (:A 3)
               (:A 4)
               (:A 5)
               (:A 7)))
(setq list (list (make-variable) (make-variable) (make-variable) (make-variable) (make-variable)))
(assert! (mapprules list prules :symbol-mode t))
(one-value (solution list (static-ordering #'linear-force)) 'fail)