(in-package :t2l)
(setq prules   '((:S :X :A :A) 
    (:S :X :A)
    (:S :A)
    (:S :S :S)
    (:X 5) 
    (:X 7) 
    (:X 8) 
    (:X 9)
    (:A 3)
    (:A 2)
    (:A 1)
    (:A -12) 
    (:A -4) 
    (:A -3)
    (:A -2)
    (:A -1)))
(setq vars (mapcar #'(lambda (x) (an-integer-betweenv 0 127)) (make-sequence 'list 12)))

(om-assert! (all-betweenv vars 60 80)
                       (mapprules vars prules :listdxx t :process-chunk-size 8)
                       vars)
(apply #'progn '((print 1)))

(om-assert!3 'a 'b)
(one-value 
 (solution (om-assert!
           (static-ordering #'linear-force)))