(in-package :t2l)
(setq list (mapcar #'(lambda (x) (an-integerv)) (make-sequence 'list 4)))
(setq prules '((:S 5 :A)
               (:S :S :S)
               (:A -3)
               (:A -2)
               (:A -1)
               (:A 1)
               (:A 2)
               (:A 3)
               (:A 4)
               (:A 5)
               (:A 7)))
(setq var (mapprules list prules :listdxx t :input-process-increment 4 :print-graph-info nil))
(assert! var)
(one-value (solution list (static-ordering #'linear-force)) 'fail)